[package]
name = "voice-chat"
version = "0.1.0-alpha.1"
description = "Voice Chat desktop client"
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1

[features]
custom-protocol = ["tauri/custom-protocol"]
